version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: db-postgres-doacoes
    ports:
      - "3333:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1
      POSTGRES_DB: db-postgres-doacoes
    volumes:
      - ./POSTGRES_DB:/var/lib/postgresql/data


